name: Node

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo 
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'

    - name: Build 
      run: |
        hugo -D --minify


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GithubBotToken }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
